In [6]:
import numpy as np

In [15]:
#How to create an empty and a full NumPy array?
empty_array = np.empty([3, 4])
print(empty_array)

full_array = np.full([3, 4], 1)
print(full_array)

[[7.51602728e-312 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.08221785e-312 1.46631893e-075 1.77234305e-051 8.07035395e+169]
 [6.87432730e-038 5.28979101e+174 1.90016708e-052 5.64832339e-038]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [17]:
#Create a Numpy array filled with all zeros
zeros = np.zeros([3, 4])
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
#Create a Numpy array filled with all ones
ones = np.ones(3)
print(ones)

[1. 1. 1.]


In [25]:
#Check whether a Numpy array contains a specified row
array = np.array([1, 2, 3, 4, 5])
value = 2
value_array = np.array(3)

contains_value = value in array.tolist()
contains_array = value_array in array.tolist()
print(array)
print(array.tolist())
print(contains_value)
print(contains_array)

[1 2 3 4 5]
[1, 2, 3, 4, 5]
True
True


In [31]:
#randomico
numeros_mega = np.random.randint(1, 61, 6)
print(numeros_mega)
print(numeros_mega[0])

[46  2  2 24 28 48]
46


In [33]:
#operacoes aritméticas
matriz_inicial = np.arange(1,5)
matriz_inicial

array([1, 2, 3, 4])

In [34]:
np.sum(matriz_inicial)

10

In [35]:
np.mean(matriz_inicial)

2.5

In [36]:
matriz_final = np.arange(5, 9)
matriz_final

array([5, 6, 7, 8])

In [37]:
np.subtract(matriz_final, matriz_inicial)

array([4, 4, 4, 4])

In [38]:
np.add(matriz_final, matriz_inicial)

array([ 6,  8, 10, 12])

In [45]:
np.append(matriz_inicial, matriz_final)

array([1, 2, 3, 4, 5, 6, 7, 8])